### ISSUE TITLE
[question] Getting approximate out-of-sample-like predictions for in-sample datapoints after .fit()

### ISSUE THREAD

**Issue by f-lng** [rnburn/bbai#1]
Hello,

Very interesting research! 

After fitting a model, is there a way to get a prediction for each training datapoint as if the model would have been trained with this datapoint being left out and then queried afterwards? 

It would be very useful to train stacked ensembles :)

Thank you very much!

**Comment by rnburn** [comment]
Thanks for the feedback.

I provide the leave-one-out errors for each data point here: 

https://github.com/rnburn/bbai/blob/master/bbai/glm/_logistic_regression.py#L112

But not the predictions; though that should be easy to add -- I'll look into supporting it.

**Comment by f-lng** [comment]
Thank you very much, I should be able to work with the errors easily :)
